# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employees',
        ),
    ]
