# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_app', '0002_delete_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('income', models.IntegerField()),
                ('expense', models.IntegerField()),
                ('savings', models.IntegerField()),
            ],
        ),
    ]
